"""Evaluate Agent answers with local checks and optional Ark/Seed judge.

Input is a JSONL file generated by generate_agent_answers.py, with fields:
scene, query, answer, expected_keywords. If ARK_API_KEY is not set, this script
still produces a local answer-quality report and marks judge results as skipped.
Real secrets must be provided via environment variables only.
"""

from __future__ import annotations

import argparse
import json
import os
import re
from dataclasses import asdict, dataclass
from datetime import datetime
from pathlib import Path
from typing import Any
from urllib.request import Request, urlopen

try:
    from evaluate_seed_dataset import normalize_text
except ModuleNotFoundError:
    from scripts.evaluate_seed_dataset import normalize_text

try:
    from utils.rag_formatting import NO_EVIDENCE_RESPONSE
except ModuleNotFoundError:
    NO_EVIDENCE_RESPONSE = "抱歉，当前知识库中没有检索到足够相关的资料，暂时无法准确回答这个问题。"

PROJECT_ROOT = Path(__file__).resolve().parents[1]
REPORT_DIR = PROJECT_ROOT / "eval" / "reports"
DEFAULT_ARK_BASE_URL = "https://ark-cn-beijing.bytedance.net/api/v3"
DEFAULT_JUDGE_MODEL = "ep-20260609191630-7gkjm"
CITATION_RE = re.compile(r"\[(\d+)\]")


@dataclass(frozen=True)
class AnswerRecord:
    scene: str
    query: str
    answer: str
    expected_keywords: list[str]


@dataclass(frozen=True)
class LocalAnswerQuality:
    matched_keywords: list[str]
    missing_keywords: list[str]
    keyword_coverage: float
    citations: list[str]
    citation_count: int
    has_citation: bool
    is_no_evidence_response: bool
    unsupported_risk: bool


@dataclass(frozen=True)
class AnswerEvalResult:
    scene: str
    query: str
    matched_keywords: list[str]
    missing_keywords: list[str]
    keyword_coverage: float
    citations: list[str]
    citation_count: int
    has_citation: bool
    is_no_evidence_response: bool
    unsupported_risk: bool
    judge_status: str
    judge_score: float | None
    judge_reason: str


def has_ark_key() -> bool:
    return bool((os.getenv("ARK_API_KEY") or "").strip())


def load_answer_records(path: Path) -> list[AnswerRecord]:
    records: list[AnswerRecord] = []
    with path.open("r", encoding="utf-8") as file:
        for line_no, line in enumerate(file, start=1):
            line = line.strip()
            if not line:
                continue
            raw = json.loads(line)
            records.append(
                AnswerRecord(
                    scene=str(raw["scene"]),
                    query=str(raw["query"]),
                    answer=str(raw.get("answer", "")),
                    expected_keywords=[str(keyword) for keyword in raw.get("expected_keywords", [])],
                )
            )
    return records


def extract_citations(answer: str) -> list[str]:
    """Extract unique numeric citation markers such as [1], [2]."""
    seen: set[str] = set()
    citations: list[str] = []
    for citation in CITATION_RE.findall(answer or ""):
        if citation not in seen:
            seen.add(citation)
            citations.append(citation)
    return citations


def is_no_evidence_answer(answer: str) -> bool:
    normalized = normalize_text(answer)
    return normalize_text(NO_EVIDENCE_RESPONSE) in normalized or "没有检索到足够相关" in normalized


def local_keyword_eval(record: AnswerRecord) -> tuple[list[str], list[str], float]:
    normalized_answer = normalize_text(record.answer)
    matched = [keyword for keyword in record.expected_keywords if normalize_text(keyword) in normalized_answer]
    missing = [keyword for keyword in record.expected_keywords if keyword not in matched]
    coverage = len(matched) / len(record.expected_keywords) if record.expected_keywords else 0.0
    return matched, missing, round(coverage, 4)


def local_answer_quality(record: AnswerRecord) -> LocalAnswerQuality:
    matched, missing, coverage = local_keyword_eval(record)
    citations = extract_citations(record.answer)
    no_evidence = is_no_evidence_answer(record.answer)
    has_citation = bool(citations)
    # 本地启发式：有内容回答但关键词覆盖不足，且没有引用/没有拒答时，标记为疑似脱离资料。
    unsupported_risk = (not no_evidence) and (coverage < 1.0) and (not has_citation)
    return LocalAnswerQuality(
        matched_keywords=matched,
        missing_keywords=missing,
        keyword_coverage=coverage,
        citations=citations,
        citation_count=len(citations),
        has_citation=has_citation,
        is_no_evidence_response=no_evidence,
        unsupported_risk=unsupported_risk,
    )


def build_judge_prompt(record: AnswerRecord) -> str:
    return (
        "你是一个严谨的智能客服答案评测员。请根据问题、答案和期望关键词判断答案质量。"
        "重点检查答案是否覆盖关键事实、是否包含形如 [1] 的资料引用、是否在资料不足时拒答。"
        "只输出 JSON，格式为 {\"score\": 0到1之间的数字, \"reason\": \"简短中文原因\"}。\n\n"
        f"场景：{record.scene}\n"
        f"问题：{record.query}\n"
        f"答案：{record.answer}\n"
        f"期望关键词：{', '.join(record.expected_keywords)}\n"
    )


def call_ark_judge(record: AnswerRecord, model: str, base_url: str, timeout: int = 60) -> tuple[float | None, str]:
    api_key = os.getenv("ARK_API_KEY", "").strip()
    url = base_url.rstrip("/") + "/chat/completions"
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": "你是一个只输出 JSON 的评测器。"},
            {"role": "user", "content": build_judge_prompt(record)},
        ],
        "temperature": 0,
    }
    request = Request(
        url,
        data=json.dumps(payload, ensure_ascii=False).encode("utf-8"),
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
        method="POST",
    )
    with urlopen(request, timeout=timeout) as response:
        raw = json.loads(response.read().decode("utf-8"))
    content = raw.get("choices", [{}])[0].get("message", {}).get("content", "{}")
    try:
        judged = json.loads(content)
        return float(judged.get("score")), str(judged.get("reason", ""))
    except (TypeError, ValueError, json.JSONDecodeError):
        return None, content[:500]


def evaluate_records(records: list[AnswerRecord], use_ark: bool, model: str, base_url: str) -> list[AnswerEvalResult]:
    results: list[AnswerEvalResult] = []
    for record in records:
        local_quality = local_answer_quality(record)
        judge_status = "skipped_no_ark_key"
        judge_score = None
        judge_reason = "ARK_API_KEY is not set; only local answer-quality evaluation was run."
        if use_ark:
            try:
                judge_score, judge_reason = call_ark_judge(record, model=model, base_url=base_url)
                judge_status = "success"
            except Exception as exc:  # noqa: BLE001 - report external judge failure without leaking key
                judge_status = "failed"
                judge_reason = f"{type(exc).__name__}: {exc}"
        results.append(
            AnswerEvalResult(
                scene=record.scene,
                query=record.query,
                matched_keywords=local_quality.matched_keywords,
                missing_keywords=local_quality.missing_keywords,
                keyword_coverage=local_quality.keyword_coverage,
                citations=local_quality.citations,
                citation_count=local_quality.citation_count,
                has_citation=local_quality.has_citation,
                is_no_evidence_response=local_quality.is_no_evidence_response,
                unsupported_risk=local_quality.unsupported_risk,
                judge_status=judge_status,
                judge_score=judge_score,
                judge_reason=judge_reason,
            )
        )
    return results


def summarize(results: list[AnswerEvalResult]) -> dict[str, Any]:
    total = len(results)
    avg_keyword = sum(result.keyword_coverage for result in results) / total if total else 0.0
    citation_rate = sum(1 for result in results if result.has_citation) / total if total else 0.0
    no_evidence_rate = sum(1 for result in results if result.is_no_evidence_response) / total if total else 0.0
    unsupported_risk_rate = sum(1 for result in results if result.unsupported_risk) / total if total else 0.0
    judged = [result for result in results if result.judge_score is not None]
    avg_judge = sum(result.judge_score or 0 for result in judged) / len(judged) if judged else None
    return {
        "total_cases": total,
        "avg_keyword_coverage": round(avg_keyword, 4),
        "citation_rate": round(citation_rate, 4),
        "no_evidence_rate": round(no_evidence_rate, 4),
        "unsupported_risk_rate": round(unsupported_risk_rate, 4),
        "judged_cases": len(judged),
        "avg_judge_score": round(avg_judge, 4) if avg_judge is not None else None,
    }


def check_thresholds(
    summary: dict[str, Any],
    min_keyword_coverage: float = 0.0,
    min_citation_rate: float = 0.0,
    max_unsupported_risk_rate: float = 1.0,
) -> list[str]:
    failures: list[str] = []
    if summary["avg_keyword_coverage"] < min_keyword_coverage:
        failures.append(
            f"avg_keyword_coverage {summary['avg_keyword_coverage']:.2%} < required {min_keyword_coverage:.2%}"
        )
    if summary["citation_rate"] < min_citation_rate:
        failures.append(f"citation_rate {summary['citation_rate']:.2%} < required {min_citation_rate:.2%}")
    if summary["unsupported_risk_rate"] > max_unsupported_risk_rate:
        failures.append(
            f"unsupported_risk_rate {summary['unsupported_risk_rate']:.2%} > allowed {max_unsupported_risk_rate:.2%}"
        )
    return failures



def write_reports(results: list[AnswerEvalResult], output_dir: Path = REPORT_DIR) -> tuple[Path, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    json_path = output_dir / f"answer_quality_{timestamp}.json"
    md_path = output_dir / f"answer_quality_{timestamp}.md"
    payload = {"summary": summarize(results), "results": [asdict(result) for result in results]}
    json_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    lines = [
        "# Agent 答案质量评测报告",
        "",
        f"生成时间：{timestamp}",
        "",
        f"- 用例数：{payload['summary']['total_cases']}",
        f"- 平均关键词覆盖率：{payload['summary']['avg_keyword_coverage']:.2%}",
        f"- 引用覆盖率：{payload['summary']['citation_rate']:.2%}",
        f"- 无证据拒答率：{payload['summary']['no_evidence_rate']:.2%}",
        f"- 疑似脱离资料率：{payload['summary']['unsupported_risk_rate']:.2%}",
        f"- Ark/Seed 已评审用例数：{payload['summary']['judged_cases']}",
        f"- Ark/Seed 平均分：{payload['summary']['avg_judge_score']}",
        "",
        "| 场景 | 问题 | 关键词覆盖率 | 引用 | 拒答 | 疑似脱离资料 | Judge状态 | Judge分数 |",
        "|---|---|---:|---|---|---|---|---:|",
    ]
    for result in results:
        citation_text = ", ".join(f"[{citation}]" for citation in result.citations) or "-"
        lines.append(
            f"| {result.scene} | {result.query} | {result.keyword_coverage:.2%} | {citation_text} | "
            f"{result.is_no_evidence_response} | {result.unsupported_risk} | {result.judge_status} | {result.judge_score} |"
        )
    md_path.write_text("\n".join(lines), encoding="utf-8")
    return json_path, md_path


def main() -> int:
    parser = argparse.ArgumentParser(description="Evaluate Agent answers with local and optional Ark judge.")
    parser.add_argument("predictions", type=Path, help="JSONL predictions generated by generate_agent_answers.py")
    parser.add_argument("--model", default=os.getenv("ARK_SEED2_PRO_MODEL", DEFAULT_JUDGE_MODEL))
    parser.add_argument("--base-url", default=os.getenv("ARK_BASE_URL", DEFAULT_ARK_BASE_URL))
    parser.add_argument("--min-keyword-coverage", type=float, default=0.0, help="Fail when average keyword coverage is below this threshold")
    parser.add_argument("--min-citation-rate", type=float, default=0.0, help="Fail when citation rate is below this threshold")
    parser.add_argument("--max-unsupported-risk-rate", type=float, default=1.0, help="Fail when unsupported risk rate is above this threshold")
    args = parser.parse_args()

    records = load_answer_records(args.predictions)
    use_ark = has_ark_key()
    results = evaluate_records(records, use_ark=use_ark, model=args.model, base_url=args.base_url)
    json_path, md_path = write_reports(results)
    summary = summarize(results)
    print(
        f"[answer-quality] cases={summary['total_cases']} "
        f"keyword_coverage={summary['avg_keyword_coverage']:.2%} "
        f"citation_rate={summary['citation_rate']:.2%} "
        f"unsupported_risk={summary['unsupported_risk_rate']:.2%} "
        f"judged={summary['judged_cases']}"
    )
    if not use_ark:
        print("[skip] ARK_API_KEY is not set; skipped Ark/Seed judge calls.")
    print(f"[report] {json_path}")
    print(f"[report] {md_path}")
    failures = check_thresholds(
        summary,
        min_keyword_coverage=args.min_keyword_coverage,
        min_citation_rate=args.min_citation_rate,
        max_unsupported_risk_rate=args.max_unsupported_risk_rate,
    )
    if failures:
        for failure in failures:
            print(f"[quality-gate][failed] {failure}")
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
